for i in range(2):
    name = input("Enter your full name")
    f_name = input("Enter your father  name")
    cnic = input("Enter your CNIC")
    age = input("Enter your age")
    contact = input("Enter your contact")
    print ("-----------------------------------------------------")
    print("This is a student informaiton that we get from user")
    print("Name \t\t "+name)
    print("Father Name \t\t "+f_name)
    print("CNIC \t\t "+cnic)
    print("Age \t\t "+age)
    print("Contact \t\t "+contact)
    print("-----------------------------------------------------")
